# Generated from modbus_kaisai_phnix.csv
# Total: 303 writable, 167 sensors, 46 switches, 34 selects

# WRITABLE PARAMETERS (Number entities)
WRITABLE_PARAMS = {
    "C01": {"name": "Manual Comp. Frequency", "address": 1218, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 120.0, "step": 10, "unit": "Hz"},
    "C02": {"name": "Min. Comp. Frequency", "address": 1219, "data_type": "DIGI1", "category": "compressor", "min": 20.0, "max": 60.0, "step": 5, "unit": "Hz"},
    "C03": {"name": "Max. Comp. Frequency", "address": 1220, "data_type": "DIGI1", "category": "compressor", "min": 30.0, "max": 120.0, "step": 5, "unit": "Hz"},
    "C04": {"name": "Model Selection", "address": 1221, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 100.0, "step": 5},
    "C05": {"name": "Min. Comp. Frequency in Cooling at Low Ambient Temp.", "address": 1222, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 60.0, "step": 5, "unit": "°C"},
    "C06": {"name": "Frequency Control Mode", "address": 1223, "data_type": "DIGI1", "category": "compressor", "min": 1.0, "max": 120.0, "step": 10, "unit": "Hz"},
    "C07": {"name": "Resonance Point 1", "address": 1224, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 120.0, "step": 10},
    "C08": {"name": "Resonance Point 2", "address": 1225, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 120.0, "step": 10},
    "C09": {"name": "Resonance Point 3", "address": 1226, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 120.0, "step": 10},
    "C10": {"name": "Min. Comp. Frequency in Heating at Low Ambient Temp.", "address": 1227, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 120.0, "step": 10, "unit": "°C"},
    "C11": {"name": "Max. Comp. Frequency in Cooling at High Ambient Temp.", "address": 1217, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 120.0, "step": 10, "unit": "°C"},
    "C12": {"name": "Max. Comp. Frequency in DHW mode", "address": 1347, "data_type": "DIGI1", "category": "compressor", "step": 1, "unit": "Hz"},
    "C13": {"name": "P of Comp. Frequency PID", "address": 1348, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 10.0, "step": 1, "unit": "Hz"},
    "C14": {"name": "I of Comp. Frequency PID", "address": 1349, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 10.0, "step": 1, "unit": "Hz"},
    "C15": {"name": "D of Comp. Frequency PID", "address": 1350, "data_type": "DIGI1", "category": "compressor", "min": 0.0, "max": 10.0, "step": 1, "unit": "Hz"},
    "compensate_offset": {"name": "compensate offset", "address": 1235, "data_type": "TEMP", "category": "compressor", "min": 0.0, "max": 75.0, "step": 0.5},
    "compensate_slope": {"name": "compensate slope", "address": 1234, "data_type": "DIGI5", "category": "compressor", "min": 0.0, "max": 3.5, "step": 0.1},
    "D01": {"name": "Ambient Temp. of Starting Defrosting", "address": 1105, "data_type": "TEMP", "category": "defrost", "min": -37.0, "max": 45.0, "step": 0.5, "unit": "°C"},
    "D02": {"name": "Heating Operation Time Before Defrosting", "address": 1106, "data_type": "DIGI1", "category": "defrost", "min": 0.0, "max": 120.0, "step": 10, "unit": "min"},
    "D03": {"name": "Interval Time Between Defrosting Cycles", "address": 1107, "data_type": "DIGI1", "category": "defrost", "min": 10.0, "max": 90.0, "step": 5, "unit": "min"},
    "D04": {"name": "Exhaust Temp. Correction for Defrosting Cycle", "address": 1108, "data_type": "TEMP", "category": "defrost", "min": 0.0, "max": 150.0, "step": 0.5, "unit": "°C"},
    "D05-1": {"name": "Defrosting Suction Pressure 1", "address": 1109, "data_type": "DIGI5", "category": "defrost", "min": 0.0, "max": 45.0, "step": 0.1, "unit": "bar"},
    "D05-2": {"name": "Defrosting Suction Pressure 2", "address": 1110, "data_type": "DIGI5", "category": "defrost", "min": 0.0, "max": 45.0, "step": 0.1, "unit": "bar"},
    "D06": {"name": "Defrosting Cycle Time Correction", "address": 1111, "data_type": "DIGI1", "category": "defrost", "min": 0.0, "max": 120.0, "step": 10, "unit": "min"},
    "D07": {"name": "Ambient Temp. of Start Sliding Defrosting", "address": 1112, "data_type": "TEMP", "category": "defrost", "min": -37.0, "max": 45.0, "step": 0.5, "unit": "°C"},
    "D08": {"name": "Suction Temp. of Start Sliding Defrosting", "address": 1113, "data_type": "TEMP", "category": "defrost", "min": -37.0, "max": 45.0, "step": 0.5, "unit": "°C"},
    "D09": {"name": "Ambient Temp. of Stop Sliding Defrosting", "address": 1114, "data_type": "TEMP", "category": "defrost", "min": -37.0, "max": 45.0, "step": 0.5, "unit": "°C"},
    "D10": {"name": "Suction Temp. of Stop Sliding Defrosting", "address": 1115, "data_type": "TEMP", "category": "defrost", "min": -37.0, "max": 45.0, "step": 0.5, "unit": "°C"},
    "D11": {"name": "Min. Inlet Water Temp. of Defrosting", "address": 1116, "data_type": "TEMP", "category": "defrost", "min": 4.0, "max": 65.0, "step": 0.5, "unit": "°C"},
    "D12": {"name": "Suction Pressure of Forced Defrosting", "address": 1117, "data_type": "DIGI5", "category": "defrost", "min": 0.0, "max": 45.0, "step": 0.1, "unit": "bar"},
    "D13": {"name": "Heating Operation Time Before Forced Defrosting", "address": 1118, "data_type": "DIGI1", "category": "defrost", "min": 0.0, "max": 360.0, "step": 10, "unit": "min"},
    "D14": {"name": "Fan Motor Power Ratio to Extend Defrosting Cycle", "address": 1119, "data_type": "DIGI9", "category": "defrost", "min": 0.0, "max": 5.0, "step": 0.1, "unit": "%"},
    "D15": {"name": "Fan Motor Power Ratio to Enter Forced Defrosting", "address": 1120, "data_type": "DIGI9", "category": "defrost", "min": 0.0, "max": 5.0, "step": 0.1, "unit": "%"},
    "D16": {"name": "Max. Fan Motor Power to Enter Forced Defrosting", "address": 1121, "data_type": "DIGI1", "category": "defrost", "min": 50.0, "max": 1000.0, "step": 10},
    "D17": {"name": "Coil Temp. of Exit Defrosting", "address": 1122, "data_type": "TEMP", "category": "defrost", "min": -37.0, "max": 45.0, "step": 0.5, "unit": "°C"},
    "D18": {"name": "Distributor Tube Temp. of Exit Defrosting", "address": 1123, "data_type": "TEMP", "category": "defrost", "min": -37.0, "max": 80.0, "step": 0.5, "unit": "°C"},
    "D19": {"name": "Max. Defrosting Time", "address": 1124, "data_type": "DIGI1", "category": "defrost", "min": 0.0, "max": 20.0, "step": 5, "unit": "min"},
    "D20": {"name": "Defrosting Frequency", "address": 1125, "data_type": "DIGI1", "category": "defrost", "min": 30.0, "max": 90.0, "step": 5, "unit": "Hz"},
    "D22": {"name": "Water Flow of Defrosting", "address": 1127, "data_type": "DIGI9", "category": "defrost", "min": 0.0, "max": 50.0, "step": 0.1, "unit": "L/min"},
    "D23": {"name": "Max. Defrosting Cycle by Fan Motor Power", "address": 1128, "data_type": "DIGI1", "category": "defrost", "min": 0.0, "max": 240.0, "step": 10},
    "D25": {"name": "Max. Water Temp. Decrease during Defrosting", "address": 1130, "data_type": "TEMP", "category": "defrost", "min": 2.0, "max": 65.0, "step": 0.5, "unit": "°C"},
    "D29": {"name": "Min. Defrost Time", "address": 1402, "data_type": "DIGI1", "category": "defrost", "min": 0.0, "max": 20.0, "step": 5, "unit": "min"},
    "D30": {"name": "Bottom Heater Delays Off Time after Defrost", "address": 1437, "data_type": "DIGI1", "category": "defrost", "min": 0.0, "max": 60.0, "step": 5, "unit": "min"},
    "DP2": {"name": "Dew Point Temp. Offset Value", "address": 1388, "data_type": "TEMP", "category": "defrost", "min": -10.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "DP2-temp": {"name": "End OT Cooling", "address": 1382, "data_type": "TEMP", "category": "defrost", "min": 4.0, "max": 25.0, "step": 0.5},
    "DP3": {"name": "Temp. diff. between indoor&outdoor temp. to stop", "address": 1389, "data_type": "TEMP", "category": "defrost", "min": 4.0, "max": 25.0, "step": 0.5, "unit": "°C"},
    "DP3-TEMP": {"name": "Offset dew point", "address": 1384, "data_type": "TEMP", "category": "defrost", "min": -10.0, "max": 10.0, "step": 0.5},
    "DefrstForceAmbient": {"name": "DefrstForceAmbient", "address": 1141, "data_type": "TEMP", "category": "defrost", "min": -30.0, "max": 30.0, "step": 0.5},
    "G01": {"name": "Disinfection Water Temp.", "address": 1152, "data_type": "TEMP", "category": "disinfection", "min": 60.0, "max": 70.0, "step": 0.5, "unit": "°C"},
    "G02": {"name": "Time Duration of Disinfection", "address": 1153, "data_type": "DIGI1", "category": "disinfection", "min": 0.0, "max": 60.0, "step": 5, "unit": "min"},
    "G03": {"name": "Disinfection Starting Time", "address": 1154, "data_type": "DIGI1", "category": "disinfection", "min": 0.0, "max": 23.0, "step": 5, "unit": "min"},
    "G04": {"name": "Interval Period of Disinfection", "address": 1155, "data_type": "DIGI1", "category": "disinfection", "min": 1.0, "max": 30.0, "step": 5},
    "E02": {"name": "Target Superheat for Heating", "address": 1132, "data_type": "TEMP", "category": "eev", "min": -20.0, "max": 20.0, "step": 0.5},
    "E03": {"name": "EEV Initial Steps for Heating", "address": 1133, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E03-1": {"name": "EEV Initial Steps for Heating1", "address": 1200, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E03-2": {"name": "EEV Initial Steps for Heating2", "address": 1142, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E03-3": {"name": "EEV Initial Steps for Heating3", "address": 1206, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E03-4": {"name": "EEV Initial Steps for Heating4", "address": 1207, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E03-5": {"name": "EEV Initial Steps for Heating5", "address": 1208, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E07": {"name": "EEV Min. Steps", "address": 1137, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E07-1": {"name": "EEV Min. Steps1", "address": 1209, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E07-2": {"name": "EEV Min. Steps2", "address": 1210, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E07-3": {"name": "EEV Min. Steps3", "address": 1211, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E07-4": {"name": "EEV Min. Steps4", "address": 1215, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E07-5": {"name": "EEV Min. Steps5", "address": 1216, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E08": {"name": "EEV Initial Steps for Cooling", "address": 1138, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E10": {"name": "EVI EEV: Initial Steps", "address": 1140, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E13": {"name": "EVI EEV Target Superheat Degree", "address": 1143, "data_type": "TEMP", "category": "eev", "min": -20.0, "max": 20.0, "step": 0.5},
    "E14": {"name": "EVI EEV Min. Steps", "address": 1144, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E17": {"name": "Defrosting EEV Steps", "address": 1147, "data_type": "DIGI1", "category": "eev", "min": 10.0, "max": 500.0, "step": 10, "unit": "steps"},
    "E18": {"name": "Target Superheat for Cooling", "address": 1148, "data_type": "TEMP", "category": "eev", "min": -10.0, "max": 10.0, "step": 0.5},
    "E19": {"name": "EEV Adjustment Range In Smart Mode", "address": 1149, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 300.0, "step": 10},
    "E20": {"name": "P of EEV PID", "address": 1351, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 10.0, "step": 1},
    "E21": {"name": "I of EEV PID", "address": 1352, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 10.0, "step": 1},
    "EMS Strategy": {"name": "EMS Strategy", "address": 8001, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 4.0, "step": 1},
    "EMS01": {"name": "Low PV Max. Load Ratio", "address": 1422, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 100.0, "step": 5, "unit": "%"},
    "EMS02": {"name": "Colling Mode Target Temp. Compen.", "address": 1423, "data_type": "TEMP", "category": "eev", "min": 0.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "EMS03": {"name": "Heating Mode Target Temp. Compen.", "address": 1424, "data_type": "TEMP", "category": "eev", "min": 0.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "EMS04": {"name": "DHW Mode Target Temp. Compen.", "address": 1425, "data_type": "TEMP", "category": "eev", "min": 0.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "EMS05": {"name": "Zone Room Target Temp. Compen.", "address": 1426, "data_type": "TEMP", "category": "eev", "min": 0.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "EMS06": {"name": "Max. Selling Power", "address": 1427, "data_type": "DIGI1", "category": "eev", "min": 0.0, "max": 6000.0, "step": 10},
    "EMS07": {"name": "Power Limit", "address": 8006, "data_type": "DIGI5", "category": "eev", "min": 0.0, "max": 99.9, "step": 0.1},
    "Electricity Price": {"name": "Electricity Price", "address": 8002, "data_type": "TEMP", "category": "eev", "step": 0.5},
    "F02": {"name": "Coil Temp.. for Max. Fan Speed in Cooling", "address": 1060, "data_type": "TEMP", "category": "fan", "min": -15.0, "max": 60.0, "step": 0.5, "unit": "°C"},
    "F03": {"name": "Coil Temp.. for Min. Fan Speed in Cooling", "address": 1062, "data_type": "TEMP", "category": "fan", "min": -15.0, "max": 60.0, "step": 0.5, "unit": "°C"},
    "F05": {"name": "Coil Temp.. for Max. Fan Speed in Heating", "address": 1066, "data_type": "TEMP", "category": "fan", "min": -15.0, "max": 60.0, "step": 0.5, "unit": "°C"},
    "F06": {"name": "Coil Temp.. for Min. Fan Speed in Heating", "address": 1068, "data_type": "TEMP", "category": "fan", "min": -15.0, "max": 60.0, "step": 0.5, "unit": "°C"},
    "F18": {"name": "Min. Fan Speed in Cooling", "address": 1081, "data_type": "DIGI1", "category": "fan", "min": 10.0, "max": 1300.0, "step": 10, "unit": "rpm"},
    "F19": {"name": "Min. Fan Speed in Heating", "address": 1083, "data_type": "DIGI1", "category": "fan", "min": 10.0, "max": 1300.0, "step": 10, "unit": "rpm"},
    "F23": {"name": "Rated DC Fan Motor Speed", "address": 1089, "data_type": "DIGI1", "category": "fan", "min": 10.0, "max": 1300.0, "step": 10, "unit": "rpm"},
    "F25": {"name": "Max. Fan Speed in Cooling", "address": 1103, "data_type": "DIGI1", "category": "fan", "min": 10.0, "max": 1300.0, "step": 10, "unit": "rpm"},
    "F26": {"name": "Max. Fan Speed in Heating", "address": 1104, "data_type": "DIGI1", "category": "fan", "min": 10.0, "max": 1300.0, "step": 10, "unit": "rpm"},
    "F28": {"name": "CT to Reduce Two Fans to One in Cooling", "address": 1101, "data_type": "TEMP", "category": "fan", "min": -30.0, "max": 60.0, "step": 0.5},
    "F29": {"name": "CT to Stop Single Fan in Cooling", "address": 1102, "data_type": "TEMP", "category": "fan", "min": -30.0, "max": 60.0, "step": 0.5},
    "FT3": {"name": "Target Temp.", "address": 1374, "data_type": "TEMP", "category": "fan", "min": 0.0, "max": 99.9, "step": 0.5, "unit": "°C"},
    "FT4": {"name": "Compressor Frequency", "address": 1375, "data_type": "DIGI1", "category": "fan", "min": 0.0, "max": 120.0, "step": 10, "unit": "Hz"},
    "FT5": {"name": "Target Speed of Fan1", "address": 1376, "data_type": "DIGI1", "category": "fan", "min": 0.0, "max": 1300.0, "step": 10, "unit": "rpm"},
    "FT6": {"name": "Target Speed of Fan2", "address": 1377, "data_type": "DIGI1", "category": "fan", "min": 0.0, "max": 1300.0, "step": 10, "unit": "rpm"},
    "FT7": {"name": "EEV Steps", "address": 1378, "data_type": "DIGI1", "category": "fan", "min": 0.0, "max": 550.0, "step": 10, "unit": "steps"},
    "FT8": {"name": "EVI Steps", "address": 1379, "data_type": "DIGI1", "category": "fan", "min": 0.0, "max": 550.0, "step": 10, "unit": "steps"},
    "FT9": {"name": "Speed of Circulation Pump", "address": 1380, "data_type": "DIGI1", "category": "fan", "min": 0.0, "max": 100.0, "step": 5},
    "Fault": {"name": "Fault", "address": 8010, "data_type": "DIGI1", "category": "fan", "step": 1},
    "/": {"name": "Unit Max. Power Limit", "address": 1405, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.9, "step": 0.1},
    "Battery Power": {"name": "Battery Power", "address": 8003, "data_type": "Float", "category": "other", "step": 1},
    "Battery SoC": {"name": "Battery SoC", "address": 8005, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 100.0, "step": 0.1},
    "IntevalSeconds": {"name": "IntervalSecondsReport", "address": 1145, "data_type": "DIGI1", "category": "other", "min": 30.0, "max": 300.0, "step": 10},
    "KG1": {"name": "Frist_Period_Power_ONOFF_Start", "address": 1256, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG10": {"name": "Fifth_Period_Power_ONOFF_End", "address": 1265, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG11": {"name": "Sixth_Period_Power_ONOFF_Start", "address": 1266, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG12": {"name": "Sixth_Period_Power_ONOFF_End", "address": 1267, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG2": {"name": "Frist_Period_Power_ONOFF_End", "address": 1257, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG3": {"name": "Second_Period_Power_ONOFF_Start", "address": 1258, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG4": {"name": "Second_Period_Power_ONOFF_End", "address": 1259, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG5": {"name": "Third_Period_Power_ONOFF_Start", "address": 1260, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG6": {"name": "Third_Period_Power_ONOFF_End", "address": 1261, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG7": {"name": "Fourth_Period_Power_ONOFF_Start", "address": 1262, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG8": {"name": "Fourth_Period_Power_ONOFF_End", "address": 1263, "data_type": "DIGI1", "category": "other", "step": 1},
    "KG9": {"name": "Fifth_Period_Power_ONOFF_Start", "address": 1264, "data_type": "DIGI1", "category": "other", "step": 1},
    "L01": {"name": "P", "address": 5091, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.0, "step": 0.1},
    "L02": {"name": "I", "address": 5092, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.0, "step": 0.1},
    "L03": {"name": "D", "address": 5093, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.0, "step": 0.1},
    "L04": {"name": "Cycle of PID", "address": 5094, "data_type": "DIGI1", "category": "other", "min": 0.0, "max": 100.0, "step": 5},
    "L05": {"name": "Percentage of Units Allowed to Defrost", "address": 5095, "data_type": "DIGI1", "category": "other", "min": 0.0, "max": 100.0, "step": 5},
    "L06": {"name": "Quantity of Units in The Project", "address": 5096, "data_type": "DIGI1", "category": "other", "min": 1.0, "max": 16.0, "step": 5},
    "L08": {"name": "Low Diff. Value of Optimal Load Ratio", "address": 5098, "data_type": "Float", "category": "other", "min": -100.0, "max": 100.0, "step": 10, "unit": "%"},
    "L09": {"name": "High Diff. Value of Optimal Load Ratio", "address": 5099, "data_type": "Float", "category": "other", "min": -100.0, "max": 100.0, "step": 10, "unit": "%"},
    "L12": {"name": "Cooling Target Temp.", "address": 5102, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "L13": {"name": "Heating Target Temp.", "address": 5103, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "L14": {"name": "DHW Target Temp.", "address": 5104, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "L15": {"name": "Max. Cooling Target Temp.", "address": 5105, "data_type": "TEMP", "category": "other", "min": -30.0, "max": 80.0, "step": 0.5, "unit": "°C"},
    "L16": {"name": "Min. Cooling Target Temp.", "address": 5106, "data_type": "TEMP", "category": "other", "min": -30.0, "max": 80.0, "step": 0.5, "unit": "°C"},
    "L17": {"name": "Max. Heating Target Temp.", "address": 5107, "data_type": "TEMP", "category": "other", "min": -30.0, "max": 90.0, "step": 0.5, "unit": "°C"},
    "L18": {"name": "Min. Heating Target Temp.", "address": 5108, "data_type": "TEMP", "category": "other", "min": -30.0, "max": 90.0, "step": 0.5, "unit": "°C"},
    "L19": {"name": "Max. DHW Target Temp.", "address": 5109, "data_type": "TEMP", "category": "other", "min": 0.0, "max": 85.0, "step": 0.5, "unit": "°C"},
    "L20": {"name": "Min. DHW Target Temp.", "address": 5110, "data_type": "TEMP", "category": "other", "min": 0.0, "max": 85.0, "step": 0.5, "unit": "°C"},
    "L23": {"name": "Slope", "address": 5113, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 3.5, "step": 0.1},
    "L24": {"name": "Offset", "address": 5114, "data_type": "TEMP", "category": "other", "min": 0.0, "max": 85.0, "step": 0.5},
    "L28": {"name": "Electric Heater On AT", "address": 5118, "data_type": "TEMP", "category": "other", "min": -30.0, "max": 60.0, "step": 0.5},
    "L29": {"name": "Electric Heater Delays On Time", "address": 5119, "data_type": "DIGI1", "category": "other", "min": 10.0, "max": 999.0, "step": 10, "unit": "min"},
    "L30": {"name": "Electric Heater Forced On Time", "address": 5120, "data_type": "DIGI1", "category": "other", "min": 10.0, "max": 1440.0, "step": 10, "unit": "min"},
    "L31": {"name": "AT to Start Electric Heater Without Delay", "address": 5121, "data_type": "TEMP", "category": "other", "min": -30.0, "max": 60.0, "step": 0.5},
    "L32": {"name": "Electric Heater Off Temp. Diff", "address": 5122, "data_type": "TEMP", "category": "other", "min": 0.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "L33": {"name": "Electric Heater Opening Temp.Diff", "address": 5123, "data_type": "TEMP", "category": "other", "min": 0.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "L34": {"name": "Electric Heater On Load", "address": 5124, "data_type": "DIGI1", "category": "other", "min": 0.0, "max": 100.0, "step": 5},
    "M1 Cooling Target": {"name": "Mode&Temp.&Power Timer1 Cooling Target", "address": 1285, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M1 End": {"name": "Mode&Temp.&Power Timer1 End", "address": 1282, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M1 Heating Target": {"name": "Mode&Temp.&Power Timer1 Heating Target", "address": 1284, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M1 Hot Water Target": {"name": "Mode&Temp.&Power Timer1 Hot Water Target", "address": 1283, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M1 Max. Power": {"name": "Mode&Temp.&Power Timer1 Max. Power", "address": 1287, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.9, "step": 0.1, "unit": "°C"},
    "M1 Start": {"name": "Mode&Temp.&Power Timer1 Start", "address": 1281, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M2 Cooling Target": {"name": "Mode&Temp.&Power Timer2 Cooling Target", "address": 1292, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M2 End": {"name": "Mode&Temp.&Power Timer2 End", "address": 1289, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M2 Heating Target": {"name": "Mode&Temp.&Power Timer2 Heating Target", "address": 1291, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M2 Hot Water Target": {"name": "Mode&Temp.&Power Timer2 Hot Water Target", "address": 1290, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M2 Max. Power": {"name": "Mode&Temp.&Power Timer2 Max. Power", "address": 1294, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.9, "step": 0.1, "unit": "°C"},
    "M2 Start": {"name": "Mode&Temp.&Power Timer2 Start", "address": 1288, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M3 Cooling Target": {"name": "Mode&Temp.&Power Timer3 Cooling Target", "address": 1299, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M3 End": {"name": "Mode&Temp.&Power Timer3 End", "address": 1296, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M3 Heating Target": {"name": "Mode&Temp.&Power Timer3 Heating Target", "address": 1298, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M3 Hot Water Target": {"name": "Mode&Temp.&Power Timer3 Hot Water Target", "address": 1297, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M3 Max. Power": {"name": "Mode&Temp.&Power Timer3 Max. Power", "address": 1301, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.9, "step": 0.1, "unit": "°C"},
    "M3 Start": {"name": "Mode&Temp.&Power Timer3 Start", "address": 1295, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M4 Cooling Target": {"name": "Mode&Temp.&Power Timer4 Cooling Target", "address": 1306, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M4 End": {"name": "Mode&Temp.&Power Timer4 End", "address": 1303, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M4 Heating Target": {"name": "Mode&Temp.&Power Timer4 Heating Target", "address": 1305, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M4 Hot Water Target": {"name": "Mode&Temp.&Power Timer4 Hot Water Target", "address": 1304, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M4 Max. Power": {"name": "Mode&Temp.&Power Timer4 Max. Power", "address": 1308, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.9, "step": 0.1, "unit": "°C"},
    "M4 Start": {"name": "Mode&Temp.&Power Timer4 Start", "address": 1302, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M5 Cooling Target": {"name": "Mode&Temp.&Power Timer5 Cooling Target", "address": 1313, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M5 End": {"name": "Mode&Temp.&Power Timer5 End", "address": 1310, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M5 Heating Target": {"name": "Mode&Temp.&Power Timer5 Heating Target", "address": 1312, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M5 Hot Water Target": {"name": "Mode&Temp.&Power Timer5 Hot Water Target", "address": 1311, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M5 Max. Power": {"name": "Mode&Temp.&Power Timer5 Max. Power", "address": 1315, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.9, "step": 0.1, "unit": "°C"},
    "M5 Start": {"name": "Mode&Temp.&Power Timer5 Start", "address": 1309, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M6 Cooling Target": {"name": "Mode&Temp.&Power Timer6 Cooling Target", "address": 1320, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M6 End": {"name": "Mode&Temp.&Power Timer6 End", "address": 1317, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "M6 Heating Target": {"name": "Mode&Temp.&Power Timer6 Heating Target", "address": 1319, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M6 Hot Water Target": {"name": "Mode&Temp.&Power Timer6 Hot Water Target", "address": 1318, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "M6 Max. Power": {"name": "Mode&Temp.&Power Timer6 Max. Power", "address": 1322, "data_type": "DIGI5", "category": "other", "min": 0.0, "max": 99.9, "step": 0.1, "unit": "°C"},
    "M6 Start": {"name": "Mode&Temp.&Power Timer6 Start", "address": 1316, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "°C"},
    "W1 End": {"name": "Warm Water Cir. Pump Timer1 End", "address": 1327, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "min"},
    "W1 Start": {"name": "Warm Water Cir. Pump Timer1 Start", "address": 1326, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "min"},
    "W2 End": {"name": "Warm Water Cir. Pump Timer2 End", "address": 1329, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "min"},
    "W2 Start": {"name": "Warm Water Cir. Pump Timer2 Start", "address": 1328, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "min"},
    "W3 End": {"name": "Warm Water Cir. Pump Timer3 End", "address": 1331, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "min"},
    "W3 Start": {"name": "Warm Water Cir. Pump Timer3 Start", "address": 1330, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "min"},
    "OnGridPower": {"name": "OnGridPower", "address": 8004, "data_type": "Float", "category": "outputs", "step": 1},
    "A03": {"name": "Shutdown Ambient Temp.", "address": 1037, "data_type": "TEMP", "category": "protection", "min": -40.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "A04": {"name": "Antifreeze Temp.", "address": 1038, "data_type": "TEMP", "category": "protection", "step": 0.5, "unit": "°C"},
    "A05": {"name": "Antifreeze Temp. Difference", "address": 1039, "data_type": "TEMP", "category": "protection", "min": 1.0, "max": 50.0, "step": 0.5, "unit": "°C"},
    "A06": {"name": "Max. Exhaust Temp.", "address": 1040, "data_type": "TEMP", "category": "protection", "min": 60.0, "max": 130.0, "step": 0.5, "unit": "°C"},
    "A22": {"name": "Min. Antifreeze Temp.", "address": 1053, "data_type": "TEMP", "category": "protection", "min": -20.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "A23": {"name": "Min. Outlet Water Temp. Protect", "address": 1043, "data_type": "TEMP", "category": "protection", "min": -30.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "A24": {"name": "Excess Temp. Diff. Between Inlet and Outlet Temp.", "address": 1044, "data_type": "TEMP", "category": "protection", "min": 0.0, "max": 30.0, "step": 0.5, "unit": "°C"},
    "A25": {"name": "Minimum Evaporation Temp. of Cooling", "address": 1055, "data_type": "TEMP", "category": "protection", "min": -50.0, "max": 30.0, "step": 0.5, "unit": "°C"},
    "A26": {"name": "Refrigerant Type", "address": 1054, "data_type": "DIGI1", "category": "protection", "min": 0.0, "max": 99.0, "step": 5},
    "A27": {"name": "Temp. Diff. of Limiting Frequency", "address": 1056, "data_type": "TEMP", "category": "protection", "min": -20.0, "max": 95.0, "step": 0.5, "unit": "°C"},
    "A28": {"name": "Temp. Diff. Between Outlet and DHW Temp.", "address": 1057, "data_type": "TEMP", "category": "protection", "min": -20.0, "max": 95.0, "step": 0.5, "unit": "°C"},
    "A30": {"name": "Min. AT for Cooling", "address": 1051, "data_type": "TEMP", "category": "protection", "min": -30.0, "max": 60.0, "step": 0.5},
    "A31": {"name": "Electric Heater On AT", "address": 1049, "data_type": "TEMP", "category": "protection", "min": -30.0, "max": 60.0, "step": 0.5},
    "A32": {"name": "Electric Heater Delays Comp. On Time", "address": 1050, "data_type": "DIGI1", "category": "protection", "min": 10.0, "max": 999.0, "step": 10, "unit": "min"},
    "A33": {"name": "Electric Heater Opening Temp. Diff", "address": 1063, "data_type": "TEMP", "category": "protection", "min": 0.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "A34": {"name": "Crank preheating time", "address": 1064, "data_type": "DIGI1", "category": "protection", "min": 0.0, "max": 360.0, "step": 10, "unit": "min"},
    "A35": {"name": "Electric Heater OFF Temp. Diff", "address": 1031, "data_type": "TEMP", "category": "protection", "min": 0.0, "max": 30.0, "step": 0.5, "unit": "°C"},
    "A38": {"name": "Low Pressure of Limiting Frequency", "address": 1342, "data_type": "DIGI5", "category": "protection", "min": 0.0, "max": 20.0, "step": 0.1, "unit": "bar"},
    "A39": {"name": "Max. Current Value", "address": 1343, "data_type": "DIGI5", "category": "protection", "min": 0.0, "max": 50.0, "step": 0.1, "unit": "A"},
    "A40": {"name": "Rated Water Flow", "address": 1344, "data_type": "DIGI9", "category": "protection", "min": 0.0, "max": 9.99, "step": 0.1, "unit": "L/min"},
    "app_heartbeat": {"name": "app_heartbeat", "address": 1191, "data_type": "DIGI1", "category": "protection", "min": 0.0, "max": 23205.0, "step": 10},
    "P02": {"name": "Interval Time", "address": 1198, "data_type": "DIGI1", "category": "pump", "min": 1.0, "max": 120.0, "step": 10, "unit": "min"},
    "P03": {"name": "Operation Duration Time", "address": 1199, "data_type": "DIGI1", "category": "pump", "min": 1.0, "max": 30.0, "step": 5, "unit": "min"},
    "P09": {"name": "Circulation Pump Protection Period", "address": 1203, "data_type": "DIGI1", "category": "pump", "min": 0.0, "max": 30.0, "step": 5},
    "P10": {"name": "Speed of Circulation Pump", "address": 1205, "data_type": "DIGI1", "category": "pump", "min": 0.0, "max": 100.0, "step": 5},
    "P11": {"name": "Target Temp. Diff. for Pump Speed Control", "address": 1432, "data_type": "TEMP", "category": "pump", "min": 0.0, "max": 20.0, "step": 0.5, "unit": "°C"},
    "P12": {"name": "Pump Speed Adjust Range for Each Period", "address": 1433, "data_type": "DIGI1", "category": "pump", "min": 0.0, "max": 10.0, "step": 1},
    "P13": {"name": "Refill Valve Start Cycle (for IDU)", "address": 1435, "data_type": "DIGI1", "category": "pump", "min": 0.0, "max": 200.0, "step": 10},
    "P14": {"name": "Refill Valve Working Duration (for IDU)", "address": 1436, "data_type": "DIGI1", "category": "pump", "min": 0.0, "max": 6000.0, "step": 10, "unit": "min"},
    "P15": {"name": "Target Water Pressure (for IDU)", "address": 1438, "data_type": "DIGI5", "category": "pump", "min": 0.0, "max": 20.0, "step": 0.1, "unit": "bar"},
    "P16": {"name": "Stop Refilling Pressure Diff. (for IDU)", "address": 1444, "data_type": "DIGI5", "category": "pump", "min": 0.0, "max": 5.0, "step": 0.1, "unit": "bar"},
    "P99": {"name": "P99", "address": 1381, "data_type": "DIGI1", "category": "pump", "min": 0.0, "max": 100.0, "step": 5},
    "R01": {"name": "Domestic Hot Water / DHW Target Temp.", "address": 1157, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R02": {"name": "Heating Target Temp.", "address": 1158, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R03": {"name": "Cooling Target Temp.", "address": 1159, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R04": {"name": "Temp. Diff. for Power-on in Heating", "address": 1160, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "R05": {"name": "Temp. Diff. for Standby in Heating", "address": 1161, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "R06": {"name": "Temp. Diff. for Power-on in Cooling", "address": 1174, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "R07": {"name": "Temp. Diff. for Standby in Cooling", "address": 1175, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "R08": {"name": "Min. Cooling Target Temp.", "address": 1162, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R09": {"name": "Max. Cooling Target Temp.", "address": 1163, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R10": {"name": "Min. Heating Target Temp.", "address": 1164, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R11": {"name": "Max. Heating Target Temp.", "address": 1165, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R15": {"name": "Temp. Diff. of Exiting Overhigh Outlet Temp.", "address": 1166, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 15.0, "step": 0.5, "unit": "°C"},
    "R16": {"name": "Temp. Diff. for Power-on in DHW", "address": 1195, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "R17": {"name": "Temp. Diff. for Standby in DHW", "address": 1196, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 10.0, "step": 0.5, "unit": "°C"},
    "R29": {"name": "Low AT for Water Temp. Limit On", "address": 1167, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R30": {"name": "Low AT for Water Temp. Limit Off", "address": 1168, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R31": {"name": "Max. Limit Outlet Water Temp. at Low AT", "address": 1169, "data_type": "TEMP", "category": "setpoints", "min": 20.0, "max": 85.0, "step": 0.5, "unit": "°C"},
    "R32": {"name": "High AT for Water Temp. Limit On", "address": 1170, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R33": {"name": "High AT for Water Temp. Limit Off", "address": 1171, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R34": {"name": "Max. Limit Outlet Water Temp. at High AT", "address": 1172, "data_type": "TEMP", "category": "setpoints", "min": 20.0, "max": 85.0, "step": 0.5, "unit": "°C"},
    "R36": {"name": "Min. DHW Target Temp.", "address": 1176, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R37": {"name": "Max. DHW Target Temp.", "address": 1177, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "R39": {"name": "AT for Auto-start Heating Mode", "address": 1192, "data_type": "TEMP", "category": "setpoints", "min": 5.0, "max": 20.0, "step": 0.5},
    "R40": {"name": "AT for Main Circulation Pump in Smart Mode", "address": 1193, "data_type": "TEMP", "category": "setpoints", "min": -10.0, "max": 60.0, "step": 0.5},
    "R41": {"name": "AT for DHW Pump in Smart Mode", "address": 1194, "data_type": "TEMP", "category": "setpoints", "min": -10.0, "max": 60.0, "step": 0.5},
    "R42": {"name": "Max. Outlet Water Temp. in Heating", "address": 1228, "data_type": "TEMP", "category": "setpoints", "min": 20.0, "max": 85.0, "step": 0.5, "unit": "°C"},
    "R43": {"name": "Max. Limit Target Water Temp. at Low AT in Heating", "address": 1229, "data_type": "TEMP", "category": "setpoints", "min": 20.0, "max": 85.0, "step": 0.5, "unit": "°C"},
    "R44": {"name": "Max. Limit Target Water Temp. at High AT in Heating", "address": 1230, "data_type": "TEMP", "category": "setpoints", "min": 20.0, "max": 85.0, "step": 0.5, "unit": "°C"},
    "R45": {"name": "AT to Start Electric Heater Without Delay", "address": 1231, "data_type": "TEMP", "category": "setpoints", "min": -50.0, "max": 20.0, "step": 0.5},
    "R46": {"name": "Temp. Diff. between Max. DHW Target Temp. & Max. Outlet Temp.", "address": 1232, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 25.0, "step": 0.5, "unit": "°C"},
    "R60": {"name": "AT to Start Frequency Limit in Cooling", "address": 1233, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 60.0, "step": 0.5, "unit": "Hz"},
    "R61": {"name": "AT to Stop Frequency Limit in Cooling", "address": 1237, "data_type": "TEMP", "category": "setpoints", "min": 0.0, "max": 60.0, "step": 0.5, "unit": "Hz"},
    "R62": {"name": "Max. Heat Pump Outlet Water Temp.", "address": 1238, "data_type": "TEMP", "category": "setpoints", "min": 40.0, "max": 95.0, "step": 0.5, "unit": "°C"},
    "R70": {"name": "Target Room Temp.", "address": 1239, "data_type": "TEMP", "category": "setpoints", "min": 5.0, "max": 27.0, "step": 0.5, "unit": "°C"},
    "R71": {"name": "Room Temp. Diff. for Power-on in Heating", "address": 1240, "data_type": "TEMP", "category": "setpoints", "min": 0.1, "max": 3.0, "step": 0.5, "unit": "°C"},
    "R72": {"name": "Room Temp. Diff. for Standby in Heating", "address": 1241, "data_type": "TEMP", "category": "setpoints", "min": 0.1, "max": 3.0, "step": 0.5, "unit": "°C"},
    "R73": {"name": "Room Temp. Diff. for Power-on in Cooling", "address": 1242, "data_type": "TEMP", "category": "setpoints", "min": 0.1, "max": 3.0, "step": 0.5, "unit": "°C"},
    "R74": {"name": "Room Temp. Diff. for Standby in Cooling", "address": 1243, "data_type": "TEMP", "category": "setpoints", "min": 0.1, "max": 3.0, "step": 0.5, "unit": "°C"},
    "RT1-10": {"name": "Thermostat1_Offset", "address": 7009, "data_type": "TEMP", "category": "setpoints", "min": 8.0, "max": 30.0, "step": 0.5},
    "RT1-2": {"name": "Thermostat1_RoomTarget", "address": 7002, "data_type": "TEMP", "category": "setpoints", "min": 8.0, "max": 30.0, "step": 0.5},
    "RT1-9": {"name": "Thermostat1_Slope", "address": 7008, "data_type": "DIGI5", "category": "setpoints", "min": 0.0, "max": 3.5, "step": 0.1},
    "RT2-10": {"name": "Thermostat2_Offset", "address": 7099, "data_type": "TEMP", "category": "setpoints", "min": 8.0, "max": 30.0, "step": 0.5},
    "RT2-2": {"name": "Thermostat2_RoomTarget", "address": 7092, "data_type": "TEMP", "category": "setpoints", "min": 8.0, "max": 30.0, "step": 0.5},
    "RT2-9": {"name": "Thermostat2_Slope", "address": 7098, "data_type": "DIGI5", "category": "setpoints", "min": 0.0, "max": 3.5, "step": 0.1},
    "SG02": {"name": "Block Time of Mode 1", "address": 1335, "data_type": "DIGI1", "category": "status", "min": 0.0, "max": 120.0, "step": 10, "unit": "min"},
    "SG03": {"name": "Limited Power in Solar Low Mode 2", "address": 1336, "data_type": "DIGI5", "category": "status", "min": 0.0, "max": 99.9, "step": 0.1},
    "SG04": {"name": "Limited Power in Solar Medium Mode 3", "address": 1337, "data_type": "DIGI5", "category": "status", "min": 0.0, "max": 99.9, "step": 0.1},
    "SG05": {"name": "Additional hot water temp. in Mode 4", "address": 1338, "data_type": "TEMP", "category": "status", "min": 0.0, "max": 25.0, "step": 0.5, "unit": "°C"},
    "SG06": {"name": "Additional heating water temp. in Mode 4", "address": 1339, "data_type": "TEMP", "category": "status", "min": 0.0, "max": 25.0, "step": 0.5, "unit": "°C"},
    "SG07": {"name": "Additional Cooling water temp. in Mode 4", "address": 1340, "data_type": "TEMP", "category": "status", "min": 0.0, "max": 25.0, "step": 0.5, "unit": "°C"},
    "H": {"name": "H", "address": 1026, "data_type": "DIGI1", "category": "system", "min": 0.0, "max": 65535.0, "step": 10},
    "H10": {"name": "Unit Address", "address": 1024, "data_type": "DIGI1", "category": "system", "min": 1.0, "max": 32.0, "step": 5},
    "H29": {"name": "Operation Code", "address": 1034, "data_type": "DIGI1", "category": "system", "min": 0.0, "max": 20.0, "step": 5, "unit": "%"},
    "H32": {"name": "Force Switch Mode Time", "address": 1045, "data_type": "DIGI1", "category": "system", "min": 1.0, "max": 300.0, "step": 10, "unit": "min"},
    "H34": {"name": "ERP Testing Mode", "address": 1020, "data_type": "DIGI1", "category": "system", "min": 0.0, "max": 3.0, "step": 1},
    "H41": {"name": "Password for unmodified parameters", "address": 1346, "data_type": "DIGI1", "category": "system", "min": 66.0, "max": 999.0, "step": 10},
    "H42": {"name": "AT for bottom plate heater turned on", "address": 1356, "data_type": "TEMP", "category": "system", "min": -20.0, "max": 20.0, "step": 0.5},
    "Test1": {"name": "Test1", "address": 1212, "data_type": "TEMP", "category": "temperatures", "min": -10.0, "max": 10.0, "step": 0.5},
    "Test11": {"name": "Test11", "address": 1353, "data_type": "TEMP", "category": "temperatures", "min": -10.0, "max": 10.0, "step": 0.5},
    "Test12": {"name": "Test12", "address": 1354, "data_type": "TEMP", "category": "temperatures", "min": -10.0, "max": 10.0, "step": 0.5},
    "Test2": {"name": "Test2", "address": 1213, "data_type": "TEMP", "category": "temperatures", "min": -10.0, "max": 10.0, "step": 0.5},
    "Test3": {"name": "Test3", "address": 1214, "data_type": "TEMP", "category": "temperatures", "min": -10.0, "max": 10.0, "step": 0.5},
    "Test9": {"name": "Test9", "address": 1355, "data_type": "TEMP", "category": "temperatures", "min": -10.0, "max": 10.0, "step": 0.5},
    "TimerMuteOffHour": {"name": "TimerMuteOffHour", "address": 1248, "data_type": "DIGI1", "category": "temperatures", "min": 0.0, "max": 23.0, "step": 5, "unit": "min"},
    "TimerMuteOffMinute": {"name": "TimerMuteOffMinute", "address": 1249, "data_type": "DIGI1", "category": "temperatures", "min": 0.0, "max": 59.0, "step": 5, "unit": "min"},
    "TimerMuteOnHour": {"name": "TimerMuteOnHour", "address": 1245, "data_type": "DIGI1", "category": "temperatures", "min": 0.0, "max": 23.0, "step": 5, "unit": "min"},
    "TimerMuteOnMinute": {"name": "TimerMuteOnMinute", "address": 1246, "data_type": "DIGI1", "category": "temperatures", "min": 0.0, "max": 59.0, "step": 5, "unit": "min"},
    "Z02": {"name": "Zone 1 Target RT", "address": 1070, "data_type": "TEMP", "category": "zones", "min": 10.0, "max": 35.0, "step": 0.5},
    "Z03": {"name": "Zone 1 RT Diff. to Start", "address": 1071, "data_type": "TEMP", "category": "zones", "min": 0.0, "max": 10.0, "step": 0.5},
    "Z04": {"name": "Zone 2 Target RT", "address": 1072, "data_type": "TEMP", "category": "zones", "min": 10.0, "max": 35.0, "step": 0.5},
    "Z05": {"name": "Zone 2 RT Diff. to Start", "address": 1073, "data_type": "TEMP", "category": "zones", "min": 0.0, "max": 10.0, "step": 0.5},
    "Z06": {"name": "Zone 1 Heating Target Outlet WT", "address": 1075, "data_type": "TEMP", "category": "zones", "step": 0.5},
    "Z07": {"name": "Zone 2 Mixing Target Outlet WT", "address": 1076, "data_type": "TEMP", "category": "zones", "step": 0.5},
    "Z08": {"name": "Mixing Valve Manual Adjustment Ratio (0% for Auto", "address": 1080, "data_type": "DIGI1", "category": "zones", "min": 0.0, "max": 100.0, "step": 5, "unit": "%"},
    "Z09": {"name": "Mixing Valve Opening Time", "address": 1082, "data_type": "DIGI1", "category": "zones", "min": 0.0, "max": 2000.0, "step": 10, "unit": "min"},
    "Z10": {"name": "Mixing Valve Closing Time", "address": 1084, "data_type": "DIGI1", "category": "zones", "min": 0.0, "max": 2000.0, "step": 10, "unit": "min"},
    "Z11": {"name": "Mixing Valve Adjustment P(PID)", "address": 1085, "data_type": "DIGI5", "category": "zones", "min": 0.0, "max": 10.0, "step": 0.1},
    "Z12": {"name": "Mixing Valve Adjustment I(PID)", "address": 1088, "data_type": "DIGI5", "category": "zones", "min": 0.0, "max": 10.0, "step": 0.1},
    "Z13": {"name": "Mixing Valve PID Period", "address": 1090, "data_type": "DIGI1", "category": "zones", "min": 1.0, "max": 20.0, "step": 5},
    "Z14": {"name": "Steps of Mixing Valve in Cooling", "address": 1134, "data_type": "DIGI1", "category": "zones", "min": 0.0, "max": 100.0, "step": 5, "unit": "steps"},
    "Z15": {"name": "Zone 2 Max. Water Target Temp.", "address": 1135, "data_type": "TEMP", "category": "zones", "step": 0.5, "unit": "°C"},
    "Z19": {"name": "Diff. of No Pump On at Low Water Temp.", "address": 1357, "data_type": "TEMP", "category": "zones", "min": 0.0, "max": 25.0, "step": 0.5, "unit": "°C"},
    "Zone 2 Cure Slope": {"name": "Zone 2 Cure Slope", "address": 1078, "data_type": "DIGI5", "category": "zones", "min": 0.0, "max": 4.0, "step": 0.1},
    "Zone 2 Curve Offset": {"name": "Zone 2 Curve Offset", "address": 1079, "data_type": "DIGI5", "category": "zones", "min": 0.0, "max": 60.0, "step": 0.1},
}

# SENSOR PARAMETERS (Read-only)
SENSOR_PARAMS = {
    "COP/EER(Total)": {"name": "COP/EER(ODU+IDU)", "address": 2060, "data_type": "DIGI9", "category": "compressor", "step": 0.1},
    "Capacity Out(IDU)": {"name": "Capacity Output(IDU)", "address": 2147, "data_type": "DIGI5", "category": "compressor", "step": 0.1},
    "Capacity Out(ODU)": {"name": "Capacity Output(ODU)", "address": 2138, "data_type": "DIGI5", "category": "compressor", "step": 0.1},
    "Capacity Out(Total)": {"name": "Capacity Output(ODU+IDU)", "address": 2059, "data_type": "DIGI5", "category": "compressor", "step": 0.1},
    "Comsuption Power-H": {"name": "Comsuption Power-H", "address": 2078, "data_type": "DIGI1", "category": "compressor", "step": 1},
    "Comsuption Power-L": {"name": "Comsuption Power-L", "address": 2079, "data_type": "DIGI1", "category": "compressor", "step": 1},
    "Cooling Con. H(ODU)": {"name": "Cooling Consumption H(ODU)", "address": 2121, "data_type": "DIGI1", "category": "compressor", "step": 1},
    "Cooling Con. L(ODU)": {"name": "Cooling Consumption L(ODU)", "address": 2122, "data_type": "DIGI1", "category": "compressor", "step": 1},
    "Cooling Gen.H(ODU)": {"name": "Cooling Generated H(ODU)", "address": 2123, "data_type": "DIGI1", "category": "compressor", "step": 1},
    "Cooling Gen.L(ODU)": {"name": "Cooling Generated L(ODU)", "address": 2124, "data_type": "DIGI1", "category": "compressor", "step": 1},
    "code_version": {"name": "Code Version", "address": 2104, "data_type": "DIGI5", "category": "compressor", "step": 0.1},
    "DHW Con. H(IDU)": {"name": "DHW Consumption/Generated H(IDU)", "address": 2142, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "DHW Con. H(ODU)": {"name": "DHW Consumption H(ODU)", "address": 2125, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "DHW Con. L(IDU)": {"name": "DHW Consumption/Generated L(IDU)", "address": 2143, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "DHW Con. L(ODU)": {"name": "DHW Consumption L(ODU)", "address": 2126, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "DHW Gen.H(ODU)": {"name": "DHW Generated H(ODU)", "address": 2127, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "DHW Gen.L(ODU)": {"name": "DHW Generated L(ODU)", "address": 2128, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "DP4": {"name": "Indoor Temp.", "address": 2178, "data_type": "TEMP", "category": "defrost", "step": 0.5, "unit": "°C"},
    "DP5": {"name": "Indoor Humidity", "address": 2179, "data_type": "TEMP", "category": "defrost", "step": 0.5},
    "DP6": {"name": "Dew Point Temp.", "address": 2180, "data_type": "TEMP", "category": "defrost", "step": 0.5, "unit": "°C"},
    "DSP_version": {"name": "DSP_version", "address": 2026, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "Display Firmware Ver": {"name": "Display Firmware Version", "address": 2113, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "DisplayCommSucess": {"name": "DisplayCommSucess", "address": 2144, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "Display_Program_Code": {"name": "Display_Program_Code", "address": 2111, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "Display_Program_Version": {"name": "Display_Program_Version", "address": 2112, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "Driver Board Status": {"name": "Driver Board Status", "address": 2080, "data_type": "DIGI1", "category": "defrost", "step": 1},
    "EEPROM": {"name": "EEPROM", "address": 2028, "data_type": "DIGI1", "category": "eev", "step": 1},
    "EMS Strategy Command": {"name": "EMS Strategy Command", "address": 2151, "data_type": "DIGI1", "category": "eev", "step": 1},
    "EMS_State": {"name": "EMS_State", "address": 2152, "data_type": "DIGI1", "category": "eev", "step": 1},
    "Electricity_Price": {"name": "Electricity_Price", "address": 2153, "data_type": "TEMP", "category": "eev", "step": 0.5},
    "Fault1": {"name": "Fault1", "address": 2085, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault10": {"name": "Fault10", "address": 2084, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault2": {"name": "Fault2", "address": 2086, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault3": {"name": "Fault3", "address": 2087, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault4": {"name": "Fault4", "address": 2088, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault5": {"name": "Fault5", "address": 2089, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault6": {"name": "Fault6", "address": 2090, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault7": {"name": "Fault7", "address": 2081, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault8": {"name": "Fault8", "address": 2082, "data_type": "BINARY", "category": "fan", "step": 1},
    "Fault9": {"name": "Fault9", "address": 2083, "data_type": "BINARY", "category": "fan", "step": 1},
    "BatteryPower": {"name": "BatteryPower", "address": 2156, "data_type": "DIGI6", "category": "other", "step": 1},
    "BatterySoC": {"name": "BatterySoC", "address": 2155, "data_type": "DIGI5", "category": "other", "step": 0.1},
    "IDU.WaterPressure": {"name": "IDU.WaterPressure", "address": 2041, "data_type": "DIGI5", "category": "other", "step": 0.1, "unit": "bar"},
    "InputCurrent1": {"name": "InputCurrent1", "address": 2029, "data_type": "DIGI5", "category": "other", "step": 0.1, "unit": "A"},
    "InputCurrent2": {"name": "InputCurrent2", "address": 2030, "data_type": "DIGI5", "category": "other", "step": 0.1, "unit": "A"},
    "InputCurrent3": {"name": "InputCurrent3", "address": 2031, "data_type": "DIGI5", "category": "other", "step": 0.1, "unit": "A"},
    "InverterCommSucess": {"name": "InverterCommSucess", "address": 2145, "data_type": "DIGI1", "category": "other", "step": 1},
    "L40": {"name": "Centralized Control Software Code", "address": 5136, "data_type": "DIGI1", "category": "other", "step": 1},
    "L41": {"name": "Centralized Control Version", "address": 5137, "data_type": "DIGI1", "category": "other", "step": 1},
    "L42": {"name": "Operating Units", "address": 5138, "data_type": "DIGI1", "category": "other", "step": 1},
    "L43": {"name": "Average Frequency of Running", "address": 5139, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "Hz"},
    "L44": {"name": "Average Load Ratio", "address": 5140, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "%"},
    "L45": {"name": "Average Inlet Water Temp. of Running", "address": 5141, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "L46": {"name": "Average Outlet Water Temp. of Running", "address": 5142, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "L47": {"name": "DHW Tank Temp.", "address": 5143, "data_type": "TEMP", "category": "other", "step": 0.5, "unit": "°C"},
    "L48": {"name": "Quantity of Units to Defrosting", "address": 5144, "data_type": "DIGI1", "category": "other", "step": 1},
    "L49": {"name": "Quantity of Units in Defrosting", "address": 5145, "data_type": "DIGI1", "category": "other", "step": 1},
    "L50": {"name": "PID Out Value", "address": 5146, "data_type": "DIGI1", "category": "other", "step": 1},
    "L52": {"name": "If change the unit mode", "address": 5148, "data_type": "DIGI1", "category": "other", "step": 1},
    "L53": {"name": "JK Power", "address": 5150, "data_type": "ENUM", "category": "other", "step": 1},
    "L54": {"name": "JK Run Mode", "address": 5151, "data_type": "ENUM", "category": "other", "step": 1},
    "L56": {"name": "OneKeyFlag", "address": 5152, "data_type": "DIGI1", "category": "other", "step": 1},
    "L57": {"name": "UnitCommFalutFlag", "address": 5153, "data_type": "DIGI1", "category": "other", "step": 1},
    "L58": {"name": "Communication Fault Rate", "address": 5154, "data_type": "DIGI1", "category": "other", "step": 1},
    "L65": {"name": "SG Run Mode", "address": 5155, "data_type": "DIGI1", "category": "other", "step": 1},
    "L66": {"name": "BMS Communication Enabled", "address": 5156, "data_type": "DIGI1", "category": "other", "step": 1},
    "Main Freq. status": {"name": "Mainboard Freq. status", "address": 2139, "data_type": "DIGI1", "category": "other", "step": 1, "unit": "Hz"},
    "MainBoard Version": {"name": "MainBoard Version", "address": 2105, "data_type": "DIGI1", "category": "other", "step": 1},
    "Mode&Temp. Status": {"name": "Mode&Temp.&Power Timer Status", "address": 2134, "data_type": "ENUM", "category": "other", "step": 1, "unit": "°C"},
    "ModeState": {"name": "Mode State", "address": 2012, "data_type": "ENUM", "category": "other", "step": 1},
    "Natural Gas Price": {"name": "Natural Gas Price", "address": 8008, "data_type": "DIGI9", "category": "other", "step": 0.1},
    "NaturalGasPrice": {"name": "NaturalGasPrice", "address": 2158, "data_type": "DIGI9", "category": "other", "step": 0.1},
    "unsupported_mode": {"name": "unsupported_mode", "address": 2110, "data_type": "DIGI1", "category": "other", "step": 1},
    "O01~023": {"name": "Load Output", "address": 2019, "data_type": "BINARY", "category": "outputs", "step": 1},
    "O15": {"name": "EEV Steps", "address": 2020, "data_type": "DIGI1", "category": "outputs", "step": 1, "unit": "steps"},
    "O17": {"name": "EVI EEV Steps", "address": 2022, "data_type": "DIGI1", "category": "outputs", "step": 1, "unit": "steps"},
    "O25": {"name": "Load Output", "address": 2018, "data_type": "BINARY", "category": "outputs", "step": 1},
    "OnGrid Power": {"name": "OnGrid Power", "address": 2154, "data_type": "DIGI6", "category": "outputs", "step": 1},
    "AT_Temp": {"name": "AT_Temp", "address": 2136, "data_type": "TEMP", "category": "protection", "step": 0.5, "unit": "°C"},
    "PFC_version": {"name": "PFC_version", "address": 2027, "data_type": "DIGI1", "category": "pump", "step": 1},
    "PV Power": {"name": "PV Power", "address": 8007, "data_type": "Float", "category": "pump", "step": 1},
    "PV_Power": {"name": "PV_Power", "address": 2157, "data_type": "DIGI6", "category": "pump", "step": 1},
    "Power In(ODU)": {"name": "Power Input(ODU)", "address": 2137, "data_type": "DIGI5", "category": "pump", "step": 0.1},
    "Power In(Total)": {"name": "Power Input(ODU+IDU)", "address": 2054, "data_type": "DIGI5", "category": "pump", "step": 0.1},
    "Power State": {"name": "Power State", "address": 2011, "data_type": "ENUM", "category": "pump", "step": 1},
    "RT1-11": {"name": "Thermostat1_StateTarget", "address": 7065, "data_type": "TEMP", "category": "setpoints", "step": 0.5},
    "RT1-4": {"name": "Thermostat1_Code", "address": 7060, "data_type": "DIGI1", "category": "setpoints", "step": 1},
    "RT1-5": {"name": "Thermostat1_Version", "address": 7061, "data_type": "DIGI1", "category": "setpoints", "step": 1},
    "RT1-6": {"name": "Thermostat1_Selection", "address": 7062, "data_type": "BINARY", "category": "setpoints", "step": 1},
    "RT1-7": {"name": "Thermostat1_RoomTemp", "address": 7063, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "RT1-8": {"name": "Thermostat1_NeedOn", "address": 7064, "data_type": "ENUM", "category": "setpoints", "step": 1},
    "RT1-Fault": {"name": "RT1-Fault", "address": 7080, "data_type": "DIGI1", "category": "setpoints", "step": 1},
    "RT2-11": {"name": "Thermostat2_StateTarget", "address": 7155, "data_type": "ENUM", "category": "setpoints", "step": 1},
    "RT2-4": {"name": "Thermostat2_Code", "address": 7150, "data_type": "DIGI1", "category": "setpoints", "step": 1},
    "RT2-5": {"name": "Thermostat2_Version", "address": 7151, "data_type": "DIGI1", "category": "setpoints", "step": 1},
    "RT2-6": {"name": "Thermostat2_Selection", "address": 7152, "data_type": "ENUM", "category": "setpoints", "step": 1},
    "RT2-7": {"name": "Thermostat2_RoomTemp", "address": 7153, "data_type": "TEMP", "category": "setpoints", "step": 0.5, "unit": "°C"},
    "RT2-8": {"name": "Thermostat2_NeedOn", "address": 7154, "data_type": "ENUM", "category": "setpoints", "step": 1},
    "RT2-Fault": {"name": "RT2-Fault", "address": 7170, "data_type": "DIGI1", "category": "setpoints", "step": 1},
    "S01~S10": {"name": "Switch State", "address": 2034, "data_type": "BINARY", "category": "status", "step": 1},
    "SG_Ready Status": {"name": "SG_Ready Status", "address": 2133, "data_type": "ENUM", "category": "status", "step": 1},
    "S_IDU": {"name": "3rd IDU Dialing Status", "address": 2040, "data_type": "DIGI1", "category": "status", "step": 1},
    "Silent_Mode": {"name": "Silent_Mode", "address": 2108, "data_type": "DIGI1", "category": "status", "step": 1},
    "H99": {"name": "DHW Temp. Sourcing", "address": 1046, "data_type": "DIGI1", "category": "system", "min": 0.0, "max": 1.0, "step": 1, "unit": "°C"},
    "Heating Con.H(IDU)": {"name": "Heating Consumption/Generated H(IDU)", "address": 2140, "data_type": "DIGI1", "category": "system", "step": 1},
    "Heating Con.H(ODU)": {"name": "Heating Consumption H(ODU)", "address": 2117, "data_type": "DIGI1", "category": "system", "step": 1},
    "Heating Con.L(IDU)": {"name": "Heating Consumption/Generated L(IDU)", "address": 2141, "data_type": "DIGI1", "category": "system", "step": 1},
    "Heating Con.L(ODU)": {"name": "Heating Consumption L(ODU)", "address": 2118, "data_type": "DIGI1", "category": "system", "step": 1},
    "Heating Gen.H(ODU)": {"name": "Heating Generated H(ODU)", "address": 2119, "data_type": "DIGI1", "category": "system", "step": 1},
    "Heating Gen.L(ODU)": {"name": "Heating Generated L(ODU)", "address": 2120, "data_type": "DIGI1", "category": "system", "step": 1},
    "T01": {"name": "Inlet Water Temp.", "address": 2045, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T02": {"name": "Outlet Water Temp.", "address": 2046, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T03": {"name": "Coil Temp.", "address": 2049, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T04": {"name": "Ambient Temp. (AT)", "address": 2048, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T05": {"name": "Suction Temp.", "address": 2051, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T06": {"name": "Antifreeze Temp.", "address": 2055, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T07": {"name": "Buffer Tank Temp.", "address": 2052, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T08": {"name": "DHW Tank Temp.", "address": 2047, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T09": {"name": "Room Temp.", "address": 2058, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T10": {"name": "EVI Inlet Temp.", "address": 2063, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T11": {"name": "EVI Outlet Temp.", "address": 2064, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T12": {"name": "Exhaust Temp.", "address": 2053, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T14": {"name": "Distributor Tube Temp.", "address": 2050, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T15": {"name": "Low Pressure", "address": 2069, "data_type": "DIGI5", "category": "temperatures", "step": 0.1, "unit": "bar"},
    "T27": {"name": "Speed of Fan Motor 1", "address": 2074, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "rpm"},
    "T28": {"name": "Speed of Fan Motor 2", "address": 2075, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "rpm"},
    "T29": {"name": "Target Speed of Fan Motor", "address": 2076, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "rpm"},
    "T30": {"name": "Compressor Frequency", "address": 2071, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "Hz"},
    "T31": {"name": "Operation Frequency of Compressor", "address": 2072, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "Hz"},
    "T32": {"name": "Max. Frequency from Comp. Driver", "address": 2073, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "Hz"},
    "T33": {"name": "IPM High Fault Temp.", "address": 2061, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T34": {"name": "AC Input Voltage", "address": 2062, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "V"},
    "T35": {"name": "AC Input Current", "address": 2057, "data_type": "DIGI5", "category": "temperatures", "step": 0.1, "unit": "A"},
    "T36": {"name": "Phase Current of Compressor", "address": 2042, "data_type": "DIGI5", "category": "temperatures", "step": 0.1, "unit": "A"},
    "T37": {"name": "DC Power Bus Voltage", "address": 2043, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "V"},
    "T38": {"name": "IPM Temp.", "address": 2044, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T39": {"name": "Water Flow Rate", "address": 2077, "data_type": "DIGI9", "category": "temperatures", "step": 0.1, "unit": "L/min"},
    "T40": {"name": "Heating Returning Water Temp.", "address": 2035, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T41": {"name": "Heating Leaving Water Temp.", "address": 2036, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T42": {"name": "Mix Tube Outlet Water Temp.", "address": 2037, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T43": {"name": "DHW Returning Water Temp.", "address": 2038, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T44": {"name": "DHW Leaving Water Temp.", "address": 2039, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T46": {"name": "Exernal Fan Motor Driver IPM Temp.", "address": 2130, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T47": {"name": "Exernal Fan Motor Driver Power", "address": 2131, "data_type": "DIGI1", "category": "temperatures", "step": 1},
    "T48": {"name": "Exernal Fan Motor Driver Current", "address": 2132, "data_type": "DIGI6", "category": "temperatures", "step": 1, "unit": "A"},
    "T49": {"name": "Evaporation Temperature", "address": 2065, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T50": {"name": "Exhaust Superheat", "address": 2066, "data_type": "TEMP", "category": "temperatures", "step": 0.5},
    "T51": {"name": "Superheat", "address": 2067, "data_type": "TEMP", "category": "temperatures", "step": 0.5},
    "T55": {"name": "Outlet Temp. after Electric Heater", "address": 2068, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "T57": {"name": "Number of startup times of the compressor", "address": 2023, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "min"},
    "T58": {"name": "Backup Heater Running Time in DHW Mode", "address": 2024, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "min"},
    "T59": {"name": "Backup Heater Running Time in Heating mode", "address": 2025, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "min"},
    "T60": {"name": "Compressor running time", "address": 2032, "data_type": "DIGI1", "category": "temperatures", "step": 1, "unit": "min"},
    "T_PWM_IN": {"name": "Main Pump Feedback PWM Duty", "address": 2116, "data_type": "DIGI1", "category": "temperatures", "step": 1},
    "T_PWM_Out": {"name": "Main Pump Speed Output PWM Duty", "address": 2115, "data_type": "DIGI1", "category": "temperatures", "step": 1},
    "T_Test01": {"name": "BufferTank Outlet(Test)", "address": 2148, "data_type": "TEMP", "category": "temperatures", "step": 0.5},
    "T_Test02": {"name": "BufferTank Inlet(Test)", "address": 2149, "data_type": "TEMP", "category": "temperatures", "step": 0.5},
    "Thermostat1_EnvTemp": {"name": "Thermostat1_EnvTemp", "address": 7006, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "Thermostat1_MuteStatus": {"name": "Thermostat1_MuteStatus", "address": 7066, "data_type": "ENUM", "category": "temperatures", "step": 1},
    "Thermostat2_EnvTemp": {"name": "Thermostat2_EnvTemp", "address": 7096, "data_type": "TEMP", "category": "temperatures", "step": 0.5, "unit": "°C"},
    "Zone 1 Room Temp": {"name": "Zone 1 Room Temp", "address": 2160, "data_type": "TEMP", "category": "zones", "step": 0.5, "unit": "°C"},
    "Zone 1 Water Target": {"name": "Zone 1 Water Target", "address": 2164, "data_type": "TEMP", "category": "zones", "step": 0.5},
    "Zone 2 Mixing Temp": {"name": "Zone 2 Mixing Temp", "address": 2161, "data_type": "TEMP", "category": "zones", "step": 0.5, "unit": "°C"},
    "Zone 2 Mixing Valve": {"name": "Zone 2 Mixing Valve Percentage", "address": 2163, "data_type": "DIGI1", "category": "zones", "step": 1},
    "Zone 2 Room Temp": {"name": "Zone 2 Room Temp", "address": 2162, "data_type": "TEMP", "category": "zones", "step": 0.5, "unit": "°C"},
    "Zone 2 Water Target": {"name": "Zone 2 Water Target", "address": 2165, "data_type": "TEMP", "category": "zones", "step": 0.5},
    "zone_mixingvalve_operation_cnt": {"name": "zone_mixingvalve_operation_cnt", "address": 2166, "data_type": "DIGI1", "category": "zones", "step": 1, "unit": "%"},
}

# SWITCH PARAMETERS (Binary on/off)
SWITCH_PARAMS = {
    "D21": {"name": "Enable Electric Heater During Defrosting", "address": 1126, "data_type": "ENUM", "category": "defrost", "min": 0.0, "max": 1.0, "step": 1},
    "D26": {"name": "Enable Defrosting Communication in Cascade", "address": 1047, "data_type": "ENUM", "category": "defrost", "min": 0.0, "max": 1.0, "step": 1},
    "DP1-temp": {"name": "Dew point monitoring", "address": 1385, "data_type": "ENUM", "category": "defrost", "min": 0.0, "max": 1.0, "step": 1},
    "G05": {"name": "Enable Disinfection", "address": 1156, "data_type": "ENUM", "category": "disinfection", "min": 0.0, "max": 1.0, "step": 1},
    "G06": {"name": "Allow Disinfection in Standby & Off Mode", "address": 1429, "data_type": "ENUM", "category": "disinfection", "min": 0.0, "max": 1.0, "step": 1},
    "E09": {"name": "EVI EEV: Adjustment Mode", "address": 1139, "data_type": "ENUM", "category": "eev", "min": 0.0, "max": 1.0, "step": 1},
    "F10": {"name": "Fan Quantity", "address": 1074, "data_type": "ENUM", "category": "fan", "min": 0.0, "max": 1.0, "step": 1},
    "F22": {"name": "Enable Manual-control Fan Speed", "address": 1087, "data_type": "ENUM", "category": "fan", "min": 0.0, "max": 1.0, "step": 1, "unit": "rpm"},
    "FT1": {"name": "Power", "address": 1372, "data_type": "ENUM", "category": "fan", "min": 0.0, "max": 1.0, "step": 1},
    "KG13~KG28": {"name": "First_Second_Period(Enable/Disable)", "address": 1268, "data_type": "BINARY", "category": "other", "step": 1},
    "KG29~KG44": {"name": "Third_Fourth_Period(Enable/Disable)", "address": 1269, "data_type": "BINARY", "category": "other", "step": 1},
    "KG45~KG60": {"name": "Fifth_Sixth_Period(Enable/Disable)", "address": 1270, "data_type": "BINARY", "category": "other", "step": 1},
    "L10": {"name": "Power", "address": 5100, "data_type": "ENUM", "category": "other", "min": 0.0, "max": 1.0, "step": 1},
    "L22": {"name": "Enable weather compensation", "address": 5112, "data_type": "ENUM", "category": "other", "min": 0.0, "max": 1.0, "step": 1},
    "L25": {"name": "Enable Energy level coordination", "address": 5115, "data_type": "ENUM", "category": "other", "min": 0.0, "max": 1.0, "step": 1},
    "M1_2 Enalbe": {"name": "Mode&Temp.&Power Timer1_2 Enalbe", "address": 1323, "data_type": "BINARY", "category": "other", "step": 1, "unit": "°C"},
    "M3_4 Enalbe": {"name": "Mode&Temp.&Power Timer3_4 Enalbe", "address": 1324, "data_type": "BINARY", "category": "other", "step": 1, "unit": "°C"},
    "M5_6 Enalbe": {"name": "Mode&Temp.&Power Timer5_6 Enalbe", "address": 1325, "data_type": "BINARY", "category": "other", "step": 1, "unit": "°C"},
    "W1_2 Enalbe": {"name": "Warm Water Cir. Pump Timer1_2 Enalbe", "address": 1332, "data_type": "BINARY", "category": "other", "step": 1, "unit": "min"},
    "W3 Enalbe": {"name": "Warm Water Cir. Pump Timer3 Enalbe", "address": 1333, "data_type": "BINARY", "category": "other", "step": 1, "unit": "min"},
    "A11": {"name": "Enable Low Pressure Sensor", "address": 1042, "data_type": "ENUM", "category": "protection", "min": 0.0, "max": 1.0, "step": 1, "unit": "bar"},
    "A21": {"name": "Ambient/Suction/Coil Sensor Type", "address": 1052, "data_type": "ENUM", "category": "protection", "min": 0.0, "max": 1.0, "step": 1},
    "A29": {"name": "Enable High Pressure Sensor", "address": 1058, "data_type": "ENUM", "category": "protection", "min": 0.0, "max": 1.0, "step": 1, "unit": "bar"},
    "P06": {"name": "Main Circulation Pump Manual Control", "address": 1202, "data_type": "ENUM", "category": "pump", "min": 0.0, "max": 1.0, "step": 1},
    "Power": {"name": "Power", "address": 1011, "data_type": "ENUM", "category": "pump", "min": 0.0, "max": 1.0, "step": 1},
    "RT1-1": {"name": "Thermostat1_Power", "address": 7001, "data_type": "ENUM", "category": "setpoints", "min": 0.0, "max": 1.0, "step": 1},
    "RT2-1": {"name": "Thermostat2_Power", "address": 7091, "data_type": "ENUM", "category": "setpoints", "min": 0.0, "max": 1.0, "step": 1},
    "SG08": {"name": "Turn on the electric heater immediately in Mode 4", "address": 1341, "data_type": "ENUM", "category": "status", "min": 0.0, "max": 1.0, "step": 1},
    "H01": {"name": "Enable Power-off Memory", "address": 1018, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1},
    "H05": {"name": "Enable Cooling Function", "address": 1021, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1},
    "H07": {"name": "Control Mode", "address": 1023, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1},
    "H20": {"name": "3-way Valve Polarity", "address": 1033, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1},
    "H21": {"name": "Temperature Unit", "address": 1029, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1, "unit": "°C"},
    "H22": {"name": "Enable Silent Mode", "address": 1030, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1},
    "H28": {"name": "Heating/Cooling and Hot Water Function Enabled", "address": 1028, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 2.0, "step": 1},
    "H33": {"name": "Fan Motor Driver and Comp. Driver Integrated", "address": 1019, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1},
    "H36": {"name": "H36/Z16 Enable Positive Weather Compensation", "address": 1236, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1},
    "H37": {"name": "DHW Temp. Sourcing", "address": 1048, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1, "unit": "°C"},
    "H45": {"name": "Enable Showing COP and Heating Output", "address": 1404, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 1.0, "step": 1},
    "hanControl": {"name": "Manual Control", "address": 1016, "data_type": "BINARY", "category": "system", "step": 1},
    "Thermostat1_Mute": {"name": "Thermostat1_Mute", "address": 7005, "data_type": "ENUM", "category": "temperatures", "min": 0.0, "max": 1.0, "step": 1},
    "Thermostat2_Mute": {"name": "Thermostat2_Mute", "address": 7095, "data_type": "ENUM", "category": "temperatures", "min": 0.0, "max": 1.0, "step": 1},
    "Timer_Mute_Off_En": {"name": "Timer_Mute_Off_En", "address": 1247, "data_type": "ENUM", "category": "temperatures", "min": 0.0, "max": 1.0, "step": 1, "unit": "min"},
    "Timer_Mute_On_En": {"name": "Timer_Mute_On_En", "address": 1244, "data_type": "ENUM", "category": "temperatures", "min": 0.0, "max": 1.0, "step": 1, "unit": "min"},
    "Z17": {"name": "Enable AT Compensation Curve Zone 2", "address": 1077, "data_type": "ENUM", "category": "zones", "min": 0.0, "max": 1.0, "step": 1},
    "Z20": {"name": "Enable Zone 1 Water Pump in Cooling", "address": 1358, "data_type": "ENUM", "category": "zones", "min": 0.0, "max": 1.0, "step": 1},
}

# SELECT PARAMETERS (Multi-option)
SELECT_PARAMS = {
    "D24": {"name": "Defrosting Heating Source in Heating / DHW Mode", "address": 1129, "data_type": "ENUM", "category": "defrost", "min": 0.0, "max": 2.0, "step": 1},
    "DP1": {"name": "Dew point control function", "address": 1387, "data_type": "ENUM", "category": "defrost", "min": 0.0, "max": 2.0, "step": 1},
    "E01": {"name": "EEV Adjust Mode", "address": 1131, "data_type": "ENUM", "category": "eev", "min": 0.0, "max": 2.0, "step": 1},
    "F01": {"name": "Fan Motor Type", "address": 1059, "data_type": "ENUM", "category": "fan", "min": 1.0, "max": 4.0, "step": 1},
    "FT0": {"name": "Factory Test Mode", "address": 1371, "data_type": "ENUM", "category": "fan", "min": 0.0, "max": 3.0, "step": 1},
    "FT2": {"name": "Mode", "address": 1373, "data_type": "ENUM", "category": "fan", "step": 1},
    "L07": {"name": "Temp. Control Selection", "address": 5097, "data_type": "ENUM", "category": "other", "min": 0.0, "max": 2.0, "step": 1, "unit": "°C"},
    "L11": {"name": "Mode", "address": 5101, "data_type": "ENUM", "category": "other", "min": 0.0, "max": 4.0, "step": 1},
    "L21": {"name": "Supported Mode of Project", "address": 5111, "data_type": "ENUM", "category": "other", "min": 1.0, "max": 6.0, "step": 1},
    "L26": {"name": "Location of Electric Heater", "address": 5116, "data_type": "ENUM", "category": "other", "min": 0.0, "max": 3.0, "step": 1},
    "L27": {"name": "Electric Heater Stage", "address": 5117, "data_type": "ENUM", "category": "other", "min": 1.0, "max": 3.0, "step": 1},
    "M1 Mode": {"name": "Mode&Temp.&Power Timer1 Mode", "address": 1286, "data_type": "ENUM", "category": "other", "step": 1, "unit": "°C"},
    "M2 Mode": {"name": "Mode&Temp.&Power Timer2 Mode", "address": 1293, "data_type": "ENUM", "category": "other", "step": 1, "unit": "°C"},
    "M3 Mode": {"name": "Mode&Temp.&Power Timer3 Mode", "address": 1300, "data_type": "ENUM", "category": "other", "step": 1, "unit": "°C"},
    "M4 Mode": {"name": "Mode&Temp.&Power Timer4 Mode", "address": 1307, "data_type": "ENUM", "category": "other", "step": 1, "unit": "°C"},
    "M5 Mode": {"name": "Mode&Temp.&Power Timer5 Mode", "address": 1314, "data_type": "ENUM", "category": "other", "step": 1, "unit": "°C"},
    "M6 Mode": {"name": "Mode&Temp.&Power Timer6 Mode", "address": 1321, "data_type": "ENUM", "category": "other", "step": 1, "unit": "°C"},
    "Mode": {"name": "Mode", "address": 1012, "data_type": "ENUM", "category": "other", "step": 1},
    "P01": {"name": "Main Circulation Pump Operation Mode", "address": 1197, "data_type": "ENUM", "category": "pump", "min": 0.0, "max": 2.0, "step": 1, "unit": "%"},
    "P05": {"name": "DHW Pump Operation Mode", "address": 1201, "data_type": "ENUM", "category": "pump", "min": 0.0, "max": 2.0, "step": 1, "unit": "%"},
    "R35": {"name": "Location of Electric Heater", "address": 1173, "data_type": "ENUM", "category": "setpoints", "min": 0.0, "max": 3.0, "step": 1},
    "RT1-3": {"name": "Thermostat1_Zone_Selection", "address": 7003, "data_type": "ENUM", "category": "setpoints", "min": 1.0, "max": 2.0, "step": 1},
    "RT2-3": {"name": "Thermostat2_Zone_Selection", "address": 7093, "data_type": "ENUM", "category": "setpoints", "min": 1.0, "max": 2.0, "step": 1},
    "SG01": {"name": "SG Ready Application", "address": 1334, "data_type": "ENUM", "category": "status", "min": 0.0, "max": 2.0, "step": 1},
    "H18": {"name": "Electric Heater Stage", "address": 1032, "data_type": "ENUM", "category": "system", "min": 1.0, "max": 3.0, "step": 1},
    "H25": {"name": "Temp. Control Selection", "address": 1035, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 3.0, "step": 1, "unit": "°C"},
    "H27": {"name": "Enable EVI", "address": 1027, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 3.0, "step": 1},
    "H30": {"name": "Indoor Unit Type", "address": 1036, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 3.0, "step": 1},
    "H31": {"name": "Circulation Pump Type", "address": 1041, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 5.0, "step": 1},
    "H38": {"name": "language", "address": 1025, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 13.0, "step": 5},
    "H40": {"name": "External pump selection", "address": 1345, "data_type": "ENUM", "category": "system", "min": 0.0, "max": 2.0, "step": 1},
    "Thermostat1_Mode": {"name": "Thermostat1_Mode", "address": 7004, "data_type": "ENUM", "category": "temperatures", "min": 0.0, "max": 4.0, "step": 1},
    "Thermostat2_Mode": {"name": "Thermostat2_Mode", "address": 7094, "data_type": "ENUM", "category": "temperatures", "min": 0.0, "max": 4.0, "step": 1},
    "Z01": {"name": "Enable Multi-Zone Control", "address": 1069, "data_type": "ENUM", "category": "zones", "min": 0.0, "max": 9.0, "step": 1},
}
